---
- name: Make sure editor config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  loop:
    - ~/.config/Code - OSS/User/
    - ~/.config/Code/User/
    - ~/.config/Cursor/User
    - ~/.config/Antigravity/User

- name: Create editor config symlinks
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: 'visual-studio-code-settings.json', dest: '~/.config/Code - OSS/User/settings.json' }
    - { src: 'visual-studio-code-keybindings.json', dest: '~/.config/Code - OSS/User/keybindings.json' }
    - { src: 'visual-studio-code-settings.json', dest: '~/.config/Code/User/settings.json' }
    - { src: 'visual-studio-code-keybindings.json', dest: '~/.config/Code/User/keybindings.json' }
    - { src: 'cursor-settings.json', dest: '~/.config/Cursor/User/settings.json' }
    - { src: 'antigravity-settings.json', dest: '~/.config/Antigravity/User/settings.json' }

- name: Create symlink for ~/.xinitrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/xinitrc"
    dest: ~/.xinitrc
    state: link
    force: true

- name: Create symlink for ~/.Xresources
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/Xresources"
    dest: ~/.Xresources
    state: link
    force: true

- name: Make sure ~/.xmonad exists
  ansible.builtin.file:
    path: ~/.xmonad
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"

- name: Create symlink for ~/.xmonad/xmonad.hs
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/xmonad.hs"
    dest: ~/.xmonad/xmonad.hs
    state: link
    force: true

- name: Create symlink for ~/.xmobarrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/xmobarrc.hs"
    dest: ~/.xmobarrc
    state: link
    force: true
