---
- name: Install xorg packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - chromium
    - code
    - firefox
    - gimp
    - glib2
    - rdesktop
    - xclip
    - xdotool
    - xmobar
    - xmonad
    - xmonad-contrib
    - xorg-appres
    - xorg-server
    - xorg-xfd
    - xorg-xfontsel
    - xorg-xlsfonts
    - xorg-xinit    # provides startx
    - xorg-xinput
    - xorg-xkill
    - xorg-xmessage # for displaying xmonad build issues when recompiling using Mod+q
    - xorg-xmodmap
    - xorg-xprop
    - xorg-xrdb
    - xorg-xsetroot
    - xorg-xwininfo
    - xterm
    - xfce4
    - xfce4-terminal
