---
- name: Make sure SSH directory exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"

- name: Copy SSH keys to target
  ansible.builtin.copy:
    src: "~/.ssh/{{ item }}"
    dest: "~/.ssh/{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
    local_follow: true
  loop:
    - id_rsa
    - id_rsa.pub
