---
- name: Rsync this repository to the target
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}"
    dest: ~/
    rsync_opts:
      - "--no-motd"
      - "--exclude=.vagrant"
      - "--exclude=.DS_Store"
