---
- name: Configure macOS
  hosts: 127.0.0.1
  connection: local
  become: false
  vars:
    dotfiles_dir: "{{ playbook_dir }}"
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Ensure this playbook only runs on macOS
      ansible.builtin.fail:
        msg: "This playbook is intended for macOS systems only"
      when: ansible_facts['os_family'] != 'Darwin'
      tags:
        - always
  tasks:
    - name: Import clone anduril task
      ansible.builtin.import_tasks: tasks/clone-anduril-into-home.yaml
    - name: Import files task
      ansible.builtin.import_tasks: tasks/files.yaml
      tags:
        - files
    - name: Import macos files task
      ansible.builtin.import_tasks: tasks/macos/files.yaml
      tags:
        - files
    - name: Import mcabber task
      ansible.builtin.import_tasks: tasks/mcabber.yaml
      tags:
        - files
    - name: Import go task
      ansible.builtin.import_tasks: tasks/go.yaml
      tags:
        - files
    - name: Import fonts task
      ansible.builtin.import_tasks: tasks/macos/fonts.yaml
      tags:
        - fonts
